stages :
  - build
  - test
  - deploy

build-job:
  stage: build
  script: echo "building"

test-job:
  stage: test
  script:
    - echo "Running curl tests"
    - chmod +x test/curltest.sh
    - ./test/curltest.sh

deploy-job:
  stage: deploy
  script: echo "deploying"