stages :
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "building & installing dependencies"
    - pip3 install --upgrade pip
    - pip3 install --user -r requirements.txt
    - pytest --version

unit-test:
  stage: test
  script:
    - echo "Running unit tests"
    - chmod +x test/unit/test_properties.py
    - pytest -v test/unit/test_properties.py

curl-test:
  stage: test
  script:
    - echo "Running curl tests"
    - chmod +x test/curltest.sh
    - ./test/curltest.sh

deploy-job:
  stage: deploy
  script:
    - echo "Deploying"

