stages :
  - build
  - test
  - deploy

build-job:
  stage: build
  script: echo "building"

test-job:
  stage: test
  script: ./test/curltest.sh

deploy-job:
  stage: deploy
  script: echo "deploying"