stages :
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "building & installing dependencies"
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install flake8
    - pip install pytest
    - pip install pytest-cov

unit-test:
  stage: test
  script:
    - echo "Running unit tests"
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install flake8
    - pip install pytest
    - pip install pytest-cov
    - pip install requests
    - pip install pymysql
    - chmod +x test/unit/test_properties.py
    - pytest -v test/unit/test_properties.py

curl-test:
  stage: test
  script:
    - echo "Running curl tests"
    - chmod +x test/curltest.sh
    - ./test/curltest.sh

deploy-job:
  stage: deploy
  #before_script:
  #  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  #  - mkdir -p ~/.ssh
  #  - eval $(ssh-agent -s)
  #  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Deploying"
    - echo "$MY_KEY" > key.txt # use " so newlines are preserved
    - chmod 600 key.txt
    - scp -i key.txt -r ./* fcv973@cs47832.fulgentcorp.com:/assignment3



